# Generated by Django 4.1.13 on 2024-10-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='event',
            field=models.CharField(default='student', max_length=50),
            preserve_default=False,
        ),
    ]
